--------------------------------------------------------
--  Fichier créé - dimanche-janvier-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTEMEDICALE
--------------------------------------------------------

  CREATE TABLE "FEDI"."ACTEMEDICALE" 
   (	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "FEDI"."CLIENT" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CMD
--------------------------------------------------------

  CREATE TABLE "FEDI"."CMD" 
   (	"NUM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(20 BYTE), 
	"D" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "FEDI"."FACTURE" 
   (	"NUM" VARCHAR2(20 BYTE), 
	"SOLDE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "FEDI"."FOURNISSEUR" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"TELF" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(8 BYTE), 
	"FACTURE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENT
--------------------------------------------------------

  CREATE TABLE "FEDI"."MEDICAMENT" 
   (	"NUM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDONNANCE
--------------------------------------------------------

  CREATE TABLE "FEDI"."ORDONNANCE" 
   (	"NUMERO" VARCHAR2(20 BYTE), 
	"DATEORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "FEDI"."PATIENT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"NUM" VARCHAR2(20 BYTE), 
	"NUMTEL" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "FEDI"."PRODUIT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"REF" VARCHAR2(20 BYTE), 
	"FOURNISSEUR" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"STOCK" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RENDEZVOUS1
--------------------------------------------------------

  CREATE TABLE "FEDI"."RENDEZVOUS1" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"DATE1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SYS_USERS
--------------------------------------------------------

  CREATE TABLE "FEDI"."SYS_USERS" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"MNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"RANK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "FEDI"."UTILISATEUR" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FEDI.ACTEMEDICALE
SET DEFINE OFF;
Insert into FEDI.ACTEMEDICALE (TYPE,PRIX) values ('757','755755');
Insert into FEDI.ACTEMEDICALE (TYPE,PRIX) values ('7','0');
REM INSERTING into FEDI.CLIENT
SET DEFINE OFF;
REM INSERTING into FEDI.CMD
SET DEFINE OFF;
REM INSERTING into FEDI.FACTURE
SET DEFINE OFF;
Insert into FEDI.FACTURE (NUM,SOLDE) values ('231','113');
REM INSERTING into FEDI.FOURNISSEUR
SET DEFINE OFF;
Insert into FEDI.FOURNISSEUR (NOM,PRENOM,TELF,ID,FACTURE) values ('bahrouni','ahmed','50806101','58964712','payee');
Insert into FEDI.FOURNISSEUR (NOM,PRENOM,TELF,ID,FACTURE) values ('bouslama','achref','58264874','10680678','non payee');
Insert into FEDI.FOURNISSEUR (NOM,PRENOM,TELF,ID,FACTURE) values ('hammouda','youssef','28754210','10680679','non payee');
Insert into FEDI.FOURNISSEUR (NOM,PRENOM,TELF,ID,FACTURE) values ('benmansour','fedi','25826729','10670688','payee');
REM INSERTING into FEDI.MEDICAMENT
SET DEFINE OFF;
Insert into FEDI.MEDICAMENT (NUM,NOM,PRIX) values ('326','mpkjnu','96455');
REM INSERTING into FEDI.ORDONNANCE
SET DEFINE OFF;
Insert into FEDI.ORDONNANCE (NUMERO,DATEORD) values ('21','30');
REM INSERTING into FEDI.PATIENT
SET DEFINE OFF;
Insert into FEDI.PATIENT (NOM,PRENOM,SEXE,NUM,NUMTEL,ADRESSE) values ('dfgff','kjji','uhiu','12','uho','mslmld');
REM INSERTING into FEDI.PRODUIT
SET DEFINE OFF;
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('7','7','7','7','7');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('gants','#1065X1','fedi','15','200');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('doliprane','12345','gadour','50','600');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('injection','#1065X2','achref','15','300');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('seringue','#1065X3','youssef','4','100');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('panadol','#1258','fedi','12','600');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('tttt','#1259','ahmed','12','400');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('sang','#1257','ahmed','12','100');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('fsgs','sfg','sgs','0','0');
Insert into FEDI.PRODUIT (NOM,REF,FOURNISSEUR,PRIX,STOCK) values ('757','757','755755','75','75');
REM INSERTING into FEDI.RENDEZVOUS1
SET DEFINE OFF;
Insert into FEDI.RENDEZVOUS1 (CODE,DATE1) values ('1','12/12/2020');
REM INSERTING into FEDI.SYS_USERS
SET DEFINE OFF;
Insert into FEDI.SYS_USERS (USERNAME,PASSWD,FNAME,MNAME,LNAME,EMAIL,RANK) values ('ahmed','bahrouni','ahmed','bo7','17','ahmed',null);
Insert into FEDI.SYS_USERS (USERNAME,PASSWD,FNAME,MNAME,LNAME,EMAIL,RANK) values ('div','0000','ahmed','ba7','ba7','pow',null);
REM INSERTING into FEDI.UTILISATEUR
SET DEFINE OFF;
Insert into FEDI.UTILISATEUR (LOGIN,TYPE,MDP) values ('ahmed','secretaire','21453');
Insert into FEDI.UTILISATEUR (LOGIN,TYPE,MDP) values ('868','secretaire','123');
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FEDI"."CLIENT_PK" ON "FEDI"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "FEDI"."PATIENT" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."PATIENT" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."PATIENT" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."PATIENT" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."PATIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."PATIENT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "FEDI"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FEDI"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "FEDI"."UTILISATEUR" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."UTILISATEUR" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."UTILISATEUR" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDONNANCE
--------------------------------------------------------

  ALTER TABLE "FEDI"."ORDONNANCE" MODIFY ("DATEORD" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."ORDONNANCE" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENDEZVOUS1
--------------------------------------------------------

  ALTER TABLE "FEDI"."RENDEZVOUS1" MODIFY ("DATE1" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."RENDEZVOUS1" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "FEDI"."FOURNISSEUR" MODIFY ("FACTURE" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."FOURNISSEUR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."FOURNISSEUR" MODIFY ("TELF" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."FOURNISSEUR" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."FOURNISSEUR" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USERS
--------------------------------------------------------

  ALTER TABLE "FEDI"."SYS_USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."SYS_USERS" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."SYS_USERS" MODIFY ("MNAME" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."SYS_USERS" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."SYS_USERS" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."SYS_USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CMD
--------------------------------------------------------

  ALTER TABLE "FEDI"."CMD" MODIFY ("D" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."CMD" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."CMD" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."CMD" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "FEDI"."FACTURE" MODIFY ("SOLDE" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."FACTURE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACTEMEDICALE
--------------------------------------------------------

  ALTER TABLE "FEDI"."ACTEMEDICALE" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENT
--------------------------------------------------------

  ALTER TABLE "FEDI"."MEDICAMENT" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."MEDICAMENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "FEDI"."MEDICAMENT" MODIFY ("NUM" NOT NULL ENABLE);
